[git_status]
conflicted = "="
ahead = "${count}⇡"
behind = "${count}⇣"
diverged = "⇕:${ahead_count}⇡${behind_count}⇣"
untracked = "${count}󰀧"
stashed = "${count}󰐃"
modified = "${count}"
staged = "${count}"
renamed = "${count}"
deleted = "${count}"
style = "red"
format = "([\\[$all_status$ahead_behind\\]]($style)) "
